name: Link Branch to Issue

on:
  push:
    branches:
      - 'issue-*'

jobs:
  link_branch_to_issue:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the code
        uses: actions/checkout@v3

      - name: Extract Issue Number
        id: extract_issue
        run: |
          ISSUE_NUMBER=$(echo "${{ github.ref }}" | grep -oP 'issue-\K[0-9]+')
          echo "ISSUE_NUMBER=$ISSUE_NUMBER" >> $GITHUB_ENV

      - name: Link branch to issue
        if: env.ISSUE_NUMBER != ''
        run: |
          curl -X POST \
            -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
            -H "Accept: application/vnd.github.v3+json" \
            https://api.github.com/repos/${{ github.repository }}/issues/${{ env.ISSUE_NUMBER }}/comments \
            -d '{"body": "Branch linked: '${{ github.ref_name }}'"}'
